services:
  - type: web
    name: nzi-bot-md
    env: node
    branch: main
    repo: https://github.com/A-S-W-I-N-S-P-A-R-K-Y/X-BOT-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true 
    envVars:
      - key: SESSION_ID
        sync: true 
      - key: DATABASE_URL
        sync: true 
      - key: SUDO
        sync: true 
